tunnel: moderai-tunnel
credentials-file: /etc/cloudflared/cert.pem

# Configurações de logging
logfile: /var/log/cloudflared.log
loglevel: info

# Configurações de transporte
transport-loglevel: warn
retries: 5

# Configurações de ingress - ordem importa!
ingress:
  # API Backend - subdomínio api.seuprojeto.com
  - hostname: api.seuprojeto.com
    service: http://localhost:4242
    originRequest:
      httpHostHeader: api.seuprojeto.com
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 100
      keepAliveTimeout: 90s
      
  # Frontend App - subdomínio app.seuprojeto.com
  - hostname: app.seuprojeto.com
    service: http://localhost:4200
    originRequest:
      httpHostHeader: app.seuprojeto.com
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 100
      keepAliveTimeout: 90s
      
  # Catch-all rule - deve ser sempre o último
  - service: http_status:404

# Configurações de métricas (opcional)
metrics: 0.0.0.0:8080

# Configurações de origem
originRequest:
  # Configurações globais para todas as origens
  noTLSVerify: false
  disableChunkedEncoding: false
  bastionMode: false
  proxyAddress: 127.0.0.1
  proxyPort: 0
  proxyType: ""
  ipRules: []
  
# Configurações de autenticação (se necessário)
# warp-routing:
#   enabled: true