version: '3.8'

services:
  backend:
    image: moderai-backend:latest
    build:
      context: ./ModerAIAPI
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.85'
          memory: 1G
        reservations:
          cpus: '0.35'
          memory: 512M
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 10
    environment:
      - V_THREADS=8
      - PORT=4242
      - NODE_ENV=production
    ports:
      - "4242:4242"
    networks:
      - infra_net

  frontend:
    image: moderai-frontend:latest
    build:
      context: ./ModerAI-Web-v2
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.5
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 3
    environment:
      - BUN_THREADS=4
      - PORT=4200
      - NODE_ENV=production
    ports:
      - "4200:4200"
    networks:
      - infra_net

networks:
  infra_net:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.1.0/24

volumes:
  backend_data:
    driver: local
  frontend_data:
    driver: local